### ISSUE TITLE
Quite critical bug - or so it seems

### ISSUE THREAD

**Issue by f-israel** [Cr1TiKa7/My.Jdownloader.Api#1]
Hi, thanks for great work but I got something very curios.

Using C# with .Net Core 2.0 and version 2.0.0 of this lib from NuGet. JdHandler is connected and exactly 1 device gets listed with GetDevices().

Code for reproduction:
`DeviceHandler JD_Device = _jd.GetDeviceHandler(_jd.GetDevices()[0])` 
Exception:
`System.NullReferenceException: "Object reference not set to an instance of an object."`
 
Not sure if this is already fixed in GitHub as I can't compile from source (missing System.Net.Http in net40).

**Comment by f-israel** [comment]
Could trace down the problem down to basically DeviceHandler.GetDirectConnectionInfos. 
Following the trace from there it get's down to JDownloaderApiHandler @ Line 89. This line should deserialize the decrypted response. But the decrypted content is
`{
  "type" : "INTERNAL_SERVER_ERROR",
  "data" : null,
  "src" : "DEVICE"
}`. Following the code the data object is used - but this is NULL. 


For now I fixed this by just including a null check in DeviceHandler.cs @ Line 104:
` if (tmp.Data == null || string.IsNullOrEmpty(tmp.Data.ToString()))`

But I guess this disabled the direct connection feature at all and needs to be looked into.

**Comment by Cr1TiKa7** [comment]
Hello @f-israel,
first of all I am really sorry for answering that late (Happy new year btw.) and thank you for the report. 
I've fixed the Issue and uploaded the new version to nuget!
