### ISSUE TITLE
[Bug??] - I am having a bug sometimes when I connect to my JDownloader instance, verbose details below

### ISSUE THREAD

**Issue by jeffward01** [Cr1TiKa7/My.Jdownloader.Api#10]
Hello!

I have a bug that I believe I found when connecting to my JDownloader instance.  This bug only occurs sometimes... Lately its been occurring more and more.  The bug appears when I try to 'connect' to my JDownloader instance using: these methods:

![image](https://user-images.githubusercontent.com/12589359/180662659-0cf21d79-54f5-4d67-bb79-36238229d624.png)

This is happening more and more.

**My Setup**

* Console App (on my desktop
* JDownloader Client (on my desktop)
* I also have set up My.Jdownloader.Org connection

See details (This is what it looks like right after the error):

![image](https://user-images.githubusercontent.com/12589359/180662722-1b5ac2e8-898e-4496-b9b8-11dbe1cf59b4.png)

Now in this screenshot I opened up My.JDownloader.org:

![image](https://user-images.githubusercontent.com/12589359/180662748-675be1fa-241b-4cdd-a618-1eb48068aa4f.png)

If I hit 'Refresh' (see screenshot) - The **Current Connections:** `0` quickly changes to `1` and then `2` - then reverts back to `0`.

![image](https://user-images.githubusercontent.com/12589359/180662790-8804162b-fe58-4b0e-be5a-7e8820c88e34.png)

Here is a screenshot of the error message. It appears that the method 'UpdateEncryptionToken' has a null value.  

![image](https://user-images.githubusercontent.com/12589359/180662828-e0d43cd3-bb20-4719-9630-9b2ddf9213cf.png)

------

Is this a bug with the SDK library? Or perhaps this is an issue on my end? I live in NYC and my internet connection is very good, I am not using a VPN.  I can help debug this issue.

Where do you think this bug originates from?

**Comment by jeffward01** [comment]
I have removed the `JDownloaderHander.Reconnect()` method, and I replaced it with the classic `JDownloaderHander.Connect(string username, string password);` method - it appears to fix this bug, for now:

![image](https://user-images.githubusercontent.com/12589359/180662920-67af8c57-0010-4b31-97c5-9f35002b7adf.png)

I will report if this error happens again


-----

In summary, as of now I suspect that this is a problem within the  `JDownloaderHander.Reconnect()` method

**Comment by jeffward01** [comment]
The error happened again, however, I believe that this is a separate error.

Basically my app does this:

1. Downloads many links (150)
2. Sleeps for 10 minutes (allows time for the links to be downloaded...)
3. Wakes up
4. Queries JDownloader packages to get current status of packages (If downloading is complete, it will loop and download 150 more links, if downloading is not complete, it will sleep for 10 more minutes, then repeat the check).

the error happens on step 4. Please see screenshots:

![image](https://user-images.githubusercontent.com/12589359/180663728-c506b5bb-899b-40ee-8cd5-15715c6c13d4.png)

Error Message:

![image](https://user-images.githubusercontent.com/12589359/180663759-78f3c623-534d-44f2-a710-38b56a300913.png)

 `"Object reference not set to an instance of an object."`
`"   at My.JDownloader.Api.ApiHandler.JDownloaderApiHandler.CallAction[T](Device device, String action, Object param, LoginObject loginObject, Boolean decryptResponse, Boolean deserialize)"`


It appears that this error occurs at a different `My.Jdownloader.API` method. It appears the error occurs at `My.JDownloader.Api.ApiHandler.JDownloaderApiHandler.CallAction[T](Device device, String action, Object param, LoginObject loginObject, Boolean decryptResponse, Boolean deserialize)`

Here it shows that my `Device` object is not null, and `isConnected = true`:

![image](https://user-images.githubusercontent.com/12589359/180663856-1009706a-4ba6-4273-a568-0605d2e389d6.png)


I believe that this might be an internal issue? The strange thing is sometimes this works, at least it used to work, but recently has not been working for me.

**Comment by Cr1TiKa7** [comment]
Thanks for the report!
I couldn't reproduce this error so it would be greate if you could provide me a sample project where you get exactly this error?
So I can debug through this to hopefully fix this

**Comment by jeffward01** [comment]
Hello!

I am revisiting this project in the next few days, if the problem occurs again, and I cannot fix it in the SDK or in my project. i will ask for your email address so I can give you access to the project

Thanks for being so responsive! you are awesome!!
