### ISSUE TITLE
LinkgrabberV2.QueryLinks gibt nur eine leere Liste zurück

### ISSUE THREAD

**Issue by Curse86** [Cr1TiKa7/My.Jdownloader.Api#3]
Hey Cr1TiKa7,

ein super Projekt hast du erstellt! Habe es getestet und leider bekomme ich keine Objekte von der Funktion "LinkgrabberV2.QueryLinks" zurück. Im JDownloader gibt es einen entsprechenden Link. Dieser ist Online. Sobald der Link im Download Bereich ist, kann ich diesen über die Funktion "DownloadsV2.QueryLinks" abrufen. Leider ist dort der Status immer = null. Mein Ziel ist es, Downloadlinks auf deren Status (Online / Offline) zu überprüfen. Mache ich etwas falsch? Gibt es evtl. noch einen anderen Ansatz mit deiner API den Onlinestatus abzugreifen? Würde mich über eine Antwort freuen!

**Comment by Cr1TiKa7** [comment]
Hallo Curse86

danke dir für den bug report!

Habe mir das Problem mal angeschaut und bemerkt das wenn der Parameter 'maxResults' nicht über 0 ist, dieser auch nicht mit an die Api mitgesendet wird. D.h. er gibt dann immer eine leere Liste zurück.

Habe das ganze entsprechend für die nächste Version korrigiert und dafür gesorgt das man über ein Objekt, welches man über einen Parameter mitgeben kann, den Rückgabewert der API einschränken kann:

```
var newRequestObj = new QueryLinksRequestObject
                    {
                        Availability = true,
                        BytesTotal = true,
                        Comment = true,
                        Enabled = true,
                        Password = true,
                        Priority = true,
                        Status = true,
                        Url = true,
                        VariantId = true,
                        VariantIcon = true,
                        VariantName = true,
                        Variants = true
                    };
                   var tmp = dHandler.LinkgrabberV2.QueryLinks(newRequestObj);
```
