### ISSUE TITLE
DownloadController.Start and DownloadController.Stop are incorrectly swapped

### ISSUE THREAD

**Issue by ronnigaba** [Cr1TiKa7/My.Jdownloader.Api#4]
Hi,

I found this in the latest version of the code (2.4.2), where it appears that the DeviceHandler.DownloadController.Stop and DeviceHandler.DownloadController.Start methods are swapped.

The Start method calls the "/downloadcontroller/stop" action and the Stop method calls the "/downloadcontroller/start" action.
![JDownlooaderIssue](https://user-images.githubusercontent.com/2811936/127186497-90762d86-cd6d-4934-89c9-d98392c8bed1.png)

**Comment by Cr1TiKa7** [comment]
Hi,

thank you for reporting this! 
It's fixed for version 2.4.3 which should be available on nuget.org within a few hours.
