### ISSUE TITLE
CleanUp returns API_COMMAND_NOT_FOUND

### ISSUE THREAD

**Issue by tprivaterep** [Cr1TiKa7/My.Jdownloader.Api#7]
Hi, I was having a problem calling Cleanup to remove some completed downloads and did a little digging and found out that CleanUp in LinkgrabberV2.cs returns this issues.

Also I had to add ", decryptResponse: true" as in the screenshot as the decryption wasn't working

![image](https://user-images.githubusercontent.com/102672045/172364786-ff3bf503-56b0-49c0-bb1d-befa23d20109.png)

Not sure if you can do anything
Thanks

**Comment by Cr1TiKa7** [comment]
Thanks for reporting!
Seems Like they have changed the endpoint url to lower case. I will fix it as soon as I am home

**Comment by Cr1TiKa7** [comment]
Sorry for taking such a long time to get this fixed... I've been really busy lately and just totally forgot about this.
However this will be fixed in 2.4.5 which is currently on it's way to the nuger repository!
